import Vue from "vue";

import vTabs from "@/components/v-tabs";
import basicContainer from "@/components/basic-container";
import vDialog from "@/components/v-dialog";
import dataList from "@/components/dataList";
import contractLayout from "@/layout/contractLayout";
import contractList from "@/components/contractList";
import empty from "@/components/empty/empty";
import approvalRecord from "@/components/approval-record";
import vUpload from "@/components/v-upload";
import vStep from "@/components/v-step";
import chooseDialog from "@/components/choose-dialog";
import customExport from "@/components/custom-export";
import vQrcode from "@/components/v-qrcode";
import screenAdapter from "@/components/screenAdapter";
import orgnaizationOfBusiness from "@/components/orgnaizationOfBusiness";
Vue.component("choose-dialog", chooseDialog);
Vue.component("contractList", contractList);
Vue.component("basic-container", basicContainer);
Vue.component("contractLayout", contractLayout);
Vue.component("v-dialog", vDialog);
Vue.component("dataList", dataList);
Vue.component("Empty", empty);
Vue.component("vQrcode", vQrcode);
Vue.component("approval-record", approvalRecord);
Vue.component("custom-export", customExport);
Vue.component("screen-adapter", screenAdapter);
Vue.component("orgnaization-business", orgnaizationOfBusiness);
Vue.component(vTabs.name, vTabs);
Vue.component(vUpload.name, vUpload);
Vue.component(vStep.name, vStep);
Vue.component(vStep.name, vStep);
